import type { Metadata } from "next";

//Titulo de la pagina
export const metadata: Metadata = {
  title: "Todos nuestros destinos",
  description: "Generated by create next app",
  icons: {
    icon: "/LogoVibrantPeru.png",
  },
};

export default function Layout({ children, }:{children: React.ReactNode;
}) {
  return <>{children}</>;
}
